import { c as createAstro, d as createComponent, r as renderTemplate, h as renderComponent, m as maybeRenderHead } from '../astro_r0D85r7m.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from './bunny-farm_TMfpIKkg.mjs';
/* empty css                          */

const $$Astro = createAstro();
const $$Index = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Index;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Accountability Bunnies", "data-astro-cid-j7pv25f6": true }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<main data-astro-cid-j7pv25f6> <section id="check-ins" class="nav-section" data-astro-cid-j7pv25f6> <h1 data-astro-cid-j7pv25f6>Check Ins</h1> <div id="check-ins-content-section" data-astro-cid-j7pv25f6> <h2 data-astro-cid-j7pv25f6>Ideal Scenario</h2> <p class="check-ins-content" data-astro-cid-j7pv25f6>Imagine your ultimate goal. The location, the people, your role. Close your eyes and imagine the tastes and smells surrounding you. The temperature. The feeling of the air on your skin. And the feeling of the things you are touching. Imagine how you feel. Write it all down.</p> <p class="check-ins-content" data-astro-cid-j7pv25f6>Keep it somewhere where you can easily find it, like a note on your night stand, or hidden between your matresses, or pinned up inside your closet. Find a place where you can easily glance at it when you feel overwhelmed and close your eyes.</p> <p class="check-ins-content" data-astro-cid-j7pv25f6>Check in with it daily or as often as you want or not at all. It's all for you. So do whatever you want.</p> <h2 data-astro-cid-j7pv25f6>Weekly</h2> <p class="check-ins-content" data-astro-cid-j7pv25f6>Each Saturday at 7pm send a text saying if goal was met and if not, why.</p> <h2 data-astro-cid-j7pv25f6>Monthly</h2> <p class="check-ins-content" data-astro-cid-j7pv25f6>On last day of the month have a call to talk about how things are going.</p> </div> </section> <section id="goals" class="nav-section" data-astro-cid-j7pv25f6> <h1 data-astro-cid-j7pv25f6>This Week's Goals</h1> <form id="input-goal-form" data-astro-cid-j7pv25f6> <input id="input-goal" type="text" name="goal" placeholder="write your goal here" data-astro-cid-j7pv25f6> <button id="add-goal-button" type="submit" data-astro-cid-j7pv25f6>+</button> <img id="goalLine" src="goalLine.svg" alt="hand drawn line" data-astro-cid-j7pv25f6> </form> <div id="goals-section" data-astro-cid-j7pv25f6> <div class="goal-item" data-astro-cid-j7pv25f6> <img class="tikbox" src="tikbox.svg" alt="hand drawn tikbox" data-astro-cid-j7pv25f6> <div class="goal-text" data-astro-cid-j7pv25f6>apply to crc positions</div> <button id="delete-goal-button" data-astro-cid-j7pv25f6>x</button> </div> <div class="goal-item" data-astro-cid-j7pv25f6> <img class="tikbox" src="tikbox.svg" alt="hand drawn tikbox" data-astro-cid-j7pv25f6> <div class="goal-text" data-astro-cid-j7pv25f6>make more copies to send out</div> <button id="delete-goal-button" data-astro-cid-j7pv25f6>x</button> </div> <!-- {
					goalsDB.map(({ description }) => (
						<div class="goal-item">
							<img class="tikbox" src="tikbox.svg" alt="hand drawn tikbox"/>
                    		<div class="goal-text">{description}</div>
                    		<button id="delete-goal-button" >x</button>
						</div>
					))
				} --> </div> </section> <section id="bunny-farm" class="nav-section" data-astro-cid-j7pv25f6> <img id="farm" src="/farm.svg" alt="Line illustration of a farm." data-astro-cid-j7pv25f6> <img id="sun" src="/sun.svg" alt="Line illustration of a sun." data-astro-cid-j7pv25f6> <p id="tap-farm-msg" data-astro-cid-j7pv25f6>Tap the farm !</p> <button id="tap-farm-button" data-astro-cid-j7pv25f6>tap here</button> <div id="bunny-pen" data-astro-cid-j7pv25f6></div> </section> <section id="main-menu" class="main-menu" data-astro-cid-j7pv25f6> <nav id="main-navigation" data-astro-cid-j7pv25f6> <button class="nav-button" data-menu="check-ins" data-astro-cid-j7pv25f6>check ins</button> <button class="nav-button" data-menu="goals" data-astro-cid-j7pv25f6>goals</button> <button class="nav-button" data-menu="bunny-farm" data-astro-cid-j7pv25f6>bunny farm</button> </nav> </section> <section id="splash-screen" class="splash-screen" data-astro-cid-j7pv25f6> <h1 id="app-title" data-astro-cid-j7pv25f6>Ac<span class="text-accent" data-astro-cid-j7pv25f6>count</span>ability</h1> <h2 id="app-sub-title" data-astro-cid-j7pv25f6>Bunnies</h2> <img id="bunny-face" src="/bunnyface.svg" alt="line art of a bunny" data-astro-cid-j7pv25f6> <button id="lets-go-button" data-astro-cid-j7pv25f6>let's go</button> </section> <button id="show-menu-button" data-astro-cid-j7pv25f6>menu</button> </main> ` })}  `;
}, "/workspaces/Accountability-Bunnies/src/pages/index.astro", void 0);

const $$file = "/workspaces/Accountability-Bunnies/src/pages/index.astro";
const $$url = "";

export { $$Index as default, $$file as file, $$url as url };
